@startuml
title Casos de Uso
skinparam shadowing false

actor Jugador as J

usecase "Gestion" as CatG
usecase "Explorar" as CatE
usecase "Combate" as CatC
usecase "Inventario" as CatI
usecase "Turno" as CatT

J --> CatG
J --> CatE
J --> CatC
J --> CatI
J --> CatT

CatG --> (Iniciar)
CatG --> (Cargar)
CatG --> (Guardar)
CatE --> (Mover)
CatE --> (Recoger)
CatE --> (Abrir Tesoro)
CatE --> (Cambiar Cueva)
CatC --> (Atacar)
CatC --> (Hechizo)
CatI --> (Usar Pocion)
CatI --> (Equipar)
CatT --> (Pasar Turno)

(Recoger) .> (Abrir Tesoro) : <<extend>>
(Atacar) .> (Hechizo) : <<extend>>
@enduml
